// Copyright (c) 2026. Licensed under AGPLv3.
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://qrckwhokwhgwnfpsnude.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yoqVunLFcQQcsRmpyo1pvg_R0tTLET4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);